// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czafxsfsmibbgnzmctpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6YWZ4c2ZzbWliYmduem1jdHBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjQ5NTQsImV4cCI6MjA2NzEwMDk1NH0.bQH98rTmYy4hM75GuObAkspP3uKKys_stWYOYX0YLKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});